<html>
    <head>
        <title>@yield('title')</title>
        @yield('head')
    </head>
    <body>
        @yield('header-top')
        @yield('menu')
        @yield('333')
        @yield('313')
        @yield('335')
        @yield('337')
        @yield('footer') 
    </body>
</html>
